//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottom
    {
        public int BottomsID { get; set; }
        public string Bottoms { get; set; }
    
        public virtual ClothingProperty ClothingProperty { get; set; }
    }
}
